[package]
name = "rapidcap-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
image.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics.workspace = true
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
windows-capture.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
